vim.cmd("sign define DiagnosticSignError text=  texthl=DiagnosticError linehl= numhl=")
vim.cmd("sign define DiagnosticSignWarn text=  texthl=DiagnosticWarn linehl= numhl=")
vim.cmd("sign define DiagnosticSignInfo text=  texthl=DiagnosticInfo linehl= numhl=")
vim.cmd("sign define DiagnosticSignHint text=  texthl= linehl= numhl=")

vim.api.nvim_set_keymap('n', 'sd', '<Cmd>lua vim.lsp.buf.definition()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'si', '<Cmd>lua vim.lsp.buf.implementation()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'sk', '<Cmd>lua vim.lsp.buf.hover()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'ss', '<Cmd>lua vim.lsp.buf.workspace_symbol()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'svd', '<Cmd>lua vim.diagnostic.open_float()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'sn', '<Cmd>lua vim.diagnostic.goto_next()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'sN', '<Cmd>lua vim.diagnostic.goto_prev()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'sa', '<Cmd>lua vim.lsp.buf.code_action()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'sr', '<Cmd>lua vim.lsp.buf.references()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'scn', '<Cmd>lua vim.lsp.buf.rename()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'sh', '<Cmd>lua vim.lsp.buf.signature_help()<CR>', {noremap = true, silent = true})